return {
  name = "Grind 75",
  slug = "grind75",
  description = "8-week structured plan by Yangshun Tay. Problems ordered easy-to-hard with time estimates per problem.",
  categories = {
    {
      name = "Week 1",
      problems = {
        { id = 1, title = "Two Sum", slug = "two-sum", difficulty = "Easy", time_mins = 15 },
        { id = 20, title = "Valid Parentheses", slug = "valid-parentheses", difficulty = "Easy", time_mins = 20 },
        { id = 21, title = "Merge Two Sorted Lists", slug = "merge-two-sorted-lists", difficulty = "Easy", time_mins = 20 },
        { id = 121, title = "Best Time to Buy and Sell Stock", slug = "best-time-to-buy-and-sell-stock", difficulty = "Easy", time_mins = 20 },
        { id = 125, title = "Valid Palindrome", slug = "valid-palindrome", difficulty = "Easy", time_mins = 15 },
        { id = 226, title = "Invert Binary Tree", slug = "invert-binary-tree", difficulty = "Easy", time_mins = 15 },
        { id = 242, title = "Valid Anagram", slug = "valid-anagram", difficulty = "Easy", time_mins = 15 },
        { id = 704, title = "Binary Search", slug = "binary-search", difficulty = "Easy", time_mins = 15 },
        { id = 733, title = "Flood Fill", slug = "flood-fill", difficulty = "Easy", time_mins = 20 },
        { id = 235, title = "Lowest Common Ancestor of a BST", slug = "lowest-common-ancestor-of-a-binary-search-tree", difficulty = "Medium", time_mins = 20 },
        { id = 110, title = "Balanced Binary Tree", slug = "balanced-binary-tree", difficulty = "Easy", time_mins = 15 },
        { id = 141, title = "Linked List Cycle", slug = "linked-list-cycle", difficulty = "Easy", time_mins = 20 },
        { id = 232, title = "Implement Queue using Stacks", slug = "implement-queue-using-stacks", difficulty = "Easy", time_mins = 20 },
      },
    },
    {
      name = "Week 2",
      problems = {
        { id = 278, title = "First Bad Version", slug = "first-bad-version", difficulty = "Easy", time_mins = 20 },
        { id = 383, title = "Ransom Note", slug = "ransom-note", difficulty = "Easy", time_mins = 15 },
        { id = 70, title = "Climbing Stairs", slug = "climbing-stairs", difficulty = "Easy", time_mins = 20 },
        { id = 409, title = "Longest Palindrome", slug = "longest-palindrome", difficulty = "Easy", time_mins = 20 },
        { id = 206, title = "Reverse Linked List", slug = "reverse-linked-list", difficulty = "Easy", time_mins = 20 },
        { id = 169, title = "Majority Element", slug = "majority-element", difficulty = "Easy", time_mins = 20 },
        { id = 67, title = "Add Binary", slug = "add-binary", difficulty = "Easy", time_mins = 15 },
        { id = 543, title = "Diameter of Binary Tree", slug = "diameter-of-binary-tree", difficulty = "Easy", time_mins = 30 },
        { id = 876, title = "Middle of the Linked List", slug = "middle-of-the-linked-list", difficulty = "Easy", time_mins = 20 },
        { id = 104, title = "Maximum Depth of Binary Tree", slug = "maximum-depth-of-binary-tree", difficulty = "Easy", time_mins = 15 },
        { id = 217, title = "Contains Duplicate", slug = "contains-duplicate", difficulty = "Easy", time_mins = 15 },
        { id = 53, title = "Maximum Subarray", slug = "maximum-subarray", difficulty = "Medium", time_mins = 20 },
      },
    },
    {
      name = "Week 3",
      problems = {
        { id = 57, title = "Insert Interval", slug = "insert-interval", difficulty = "Medium", time_mins = 25 },
        { id = 542, title = "01 Matrix", slug = "01-matrix", difficulty = "Medium", time_mins = 30 },
        { id = 973, title = "K Closest Points to Origin", slug = "k-closest-points-to-origin", difficulty = "Medium", time_mins = 30 },
        { id = 3, title = "Longest Substring Without Repeating Characters", slug = "longest-substring-without-repeating-characters", difficulty = "Medium", time_mins = 30 },
        { id = 15, title = "3Sum", slug = "3sum", difficulty = "Medium", time_mins = 30 },
        { id = 102, title = "Binary Tree Level Order Traversal", slug = "binary-tree-level-order-traversal", difficulty = "Medium", time_mins = 20 },
        { id = 133, title = "Clone Graph", slug = "clone-graph", difficulty = "Medium", time_mins = 25 },
        { id = 150, title = "Evaluate Reverse Polish Notation", slug = "evaluate-reverse-polish-notation", difficulty = "Medium", time_mins = 30 },
      },
    },
    {
      name = "Week 4",
      problems = {
        { id = 207, title = "Course Schedule", slug = "course-schedule", difficulty = "Medium", time_mins = 30 },
        { id = 208, title = "Implement Trie (Prefix Tree)", slug = "implement-trie-prefix-tree", difficulty = "Medium", time_mins = 35 },
        { id = 322, title = "Coin Change", slug = "coin-change", difficulty = "Medium", time_mins = 25 },
        { id = 238, title = "Product of Array Except Self", slug = "product-of-array-except-self", difficulty = "Medium", time_mins = 30 },
        { id = 155, title = "Min Stack", slug = "min-stack", difficulty = "Medium", time_mins = 20 },
        { id = 98, title = "Validate Binary Search Tree", slug = "validate-binary-search-tree", difficulty = "Medium", time_mins = 20 },
        { id = 200, title = "Number of Islands", slug = "number-of-islands", difficulty = "Medium", time_mins = 25 },
        { id = 994, title = "Rotting Oranges", slug = "rotting-oranges", difficulty = "Medium", time_mins = 30 },
      },
    },
    {
      name = "Week 5",
      problems = {
        { id = 33, title = "Search in Rotated Sorted Array", slug = "search-in-rotated-sorted-array", difficulty = "Medium", time_mins = 30 },
        { id = 39, title = "Combination Sum", slug = "combination-sum", difficulty = "Medium", time_mins = 30 },
        { id = 46, title = "Permutations", slug = "permutations", difficulty = "Medium", time_mins = 30 },
        { id = 56, title = "Merge Intervals", slug = "merge-intervals", difficulty = "Medium", time_mins = 30 },
        { id = 236, title = "Lowest Common Ancestor of a Binary Tree", slug = "lowest-common-ancestor-of-a-binary-tree", difficulty = "Medium", time_mins = 25 },
        { id = 981, title = "Time Based Key-Value Store", slug = "time-based-key-value-store", difficulty = "Medium", time_mins = 35 },
        { id = 721, title = "Accounts Merge", slug = "accounts-merge", difficulty = "Medium", time_mins = 30 },
        { id = 75, title = "Sort Colors", slug = "sort-colors", difficulty = "Medium", time_mins = 25 },
      },
    },
    {
      name = "Week 6",
      problems = {
        { id = 139, title = "Word Break", slug = "word-break", difficulty = "Medium", time_mins = 30 },
        { id = 416, title = "Partition Equal Subset Sum", slug = "partition-equal-subset-sum", difficulty = "Medium", time_mins = 30 },
        { id = 8, title = "String to Integer (atoi)", slug = "string-to-integer-atoi", difficulty = "Medium", time_mins = 25 },
        { id = 54, title = "Spiral Matrix", slug = "spiral-matrix", difficulty = "Medium", time_mins = 25 },
        { id = 78, title = "Subsets", slug = "subsets", difficulty = "Medium", time_mins = 30 },
        { id = 199, title = "Binary Tree Right Side View", slug = "binary-tree-right-side-view", difficulty = "Medium", time_mins = 20 },
        { id = 5, title = "Longest Palindromic Substring", slug = "longest-palindromic-substring", difficulty = "Medium", time_mins = 25 },
        { id = 62, title = "Unique Paths", slug = "unique-paths", difficulty = "Medium", time_mins = 20 },
        { id = 105, title = "Construct Binary Tree from Preorder and Inorder", slug = "construct-binary-tree-from-preorder-and-inorder-traversal", difficulty = "Medium", time_mins = 25 },
      },
    },
    {
      name = "Week 7",
      problems = {
        { id = 11, title = "Container With Most Water", slug = "container-with-most-water", difficulty = "Medium", time_mins = 35 },
        { id = 17, title = "Letter Combinations of a Phone Number", slug = "letter-combinations-of-a-phone-number", difficulty = "Medium", time_mins = 30 },
        { id = 79, title = "Word Search", slug = "word-search", difficulty = "Medium", time_mins = 30 },
        { id = 438, title = "Find All Anagrams in a String", slug = "find-all-anagrams-in-a-string", difficulty = "Medium", time_mins = 25 },
        { id = 310, title = "Minimum Height Trees", slug = "minimum-height-trees", difficulty = "Medium", time_mins = 30 },
        { id = 621, title = "Task Scheduler", slug = "task-scheduler", difficulty = "Medium", time_mins = 35 },
        { id = 146, title = "LRU Cache", slug = "lru-cache", difficulty = "Medium", time_mins = 30 },
      },
    },
    {
      name = "Week 8",
      problems = {
        { id = 230, title = "Kth Smallest Element in a BST", slug = "kth-smallest-element-in-a-bst", difficulty = "Medium", time_mins = 25 },
        { id = 76, title = "Minimum Window Substring", slug = "minimum-window-substring", difficulty = "Hard", time_mins = 30 },
        { id = 297, title = "Serialize and Deserialize Binary Tree", slug = "serialize-and-deserialize-binary-tree", difficulty = "Hard", time_mins = 40 },
        { id = 42, title = "Trapping Rain Water", slug = "trapping-rain-water", difficulty = "Hard", time_mins = 35 },
        { id = 295, title = "Find Median from Data Stream", slug = "find-median-from-data-stream", difficulty = "Hard", time_mins = 30 },
        { id = 127, title = "Word Ladder", slug = "word-ladder", difficulty = "Hard", time_mins = 45 },
        { id = 224, title = "Basic Calculator", slug = "basic-calculator", difficulty = "Hard", time_mins = 40 },
        { id = 1235, title = "Maximum Profit in Job Scheduling", slug = "maximum-profit-in-job-scheduling", difficulty = "Hard", time_mins = 45 },
        { id = 23, title = "Merge k Sorted Lists", slug = "merge-k-sorted-lists", difficulty = "Hard", time_mins = 30 },
        { id = 84, title = "Largest Rectangle in Histogram", slug = "largest-rectangle-in-histogram", difficulty = "Hard", time_mins = 35 },
      },
    },
  },
}
