return {
  name = "NeetCode 150",
  slug = "neetcode150",
  description = "150 problems organized by pattern. Covers all common interview patterns with multiple difficulty levels per topic.",
  categories = {
    {
      name = "Arrays & Hashing",
      problems = {
        { id = 217, title = "Contains Duplicate", slug = "contains-duplicate", difficulty = "Easy" },
        { id = 242, title = "Valid Anagram", slug = "valid-anagram", difficulty = "Easy" },
        { id = 1, title = "Two Sum", slug = "two-sum", difficulty = "Easy" },
        { id = 49, title = "Group Anagrams", slug = "group-anagrams", difficulty = "Medium" },
        { id = 347, title = "Top K Frequent Elements", slug = "top-k-frequent-elements", difficulty = "Medium" },
        { id = 238, title = "Product of Array Except Self", slug = "product-of-array-except-self", difficulty = "Medium" },
        { id = 36, title = "Valid Sudoku", slug = "valid-sudoku", difficulty = "Medium" },
        { id = 128, title = "Longest Consecutive Sequence", slug = "longest-consecutive-sequence", difficulty = "Medium" },
      },
    },
    {
      name = "Two Pointers",
      problems = {
        { id = 125, title = "Valid Palindrome", slug = "valid-palindrome", difficulty = "Easy" },
        { id = 167, title = "Two Sum II", slug = "two-sum-ii-input-array-is-sorted", difficulty = "Medium" },
        { id = 15, title = "3Sum", slug = "3sum", difficulty = "Medium" },
        { id = 11, title = "Container With Most Water", slug = "container-with-most-water", difficulty = "Medium" },
        { id = 42, title = "Trapping Rain Water", slug = "trapping-rain-water", difficulty = "Hard" },
      },
    },
    {
      name = "Sliding Window",
      problems = {
        { id = 121, title = "Best Time to Buy and Sell Stock", slug = "best-time-to-buy-and-sell-stock", difficulty = "Easy" },
        { id = 3, title = "Longest Substring Without Repeating Characters", slug = "longest-substring-without-repeating-characters", difficulty = "Medium" },
        { id = 424, title = "Longest Repeating Character Replacement", slug = "longest-repeating-character-replacement", difficulty = "Medium" },
        { id = 567, title = "Permutation in String", slug = "permutation-in-string", difficulty = "Medium" },
        { id = 76, title = "Minimum Window Substring", slug = "minimum-window-substring", difficulty = "Hard" },
        { id = 239, title = "Sliding Window Maximum", slug = "sliding-window-maximum", difficulty = "Hard" },
      },
    },
    {
      name = "Stack",
      problems = {
        { id = 20, title = "Valid Parentheses", slug = "valid-parentheses", difficulty = "Easy" },
        { id = 155, title = "Min Stack", slug = "min-stack", difficulty = "Medium" },
        { id = 150, title = "Evaluate Reverse Polish Notation", slug = "evaluate-reverse-polish-notation", difficulty = "Medium" },
        { id = 22, title = "Generate Parentheses", slug = "generate-parentheses", difficulty = "Medium" },
        { id = 739, title = "Daily Temperatures", slug = "daily-temperatures", difficulty = "Medium" },
        { id = 853, title = "Car Fleet", slug = "car-fleet", difficulty = "Medium" },
        { id = 84, title = "Largest Rectangle in Histogram", slug = "largest-rectangle-in-histogram", difficulty = "Hard" },
      },
    },
    {
      name = "Binary Search",
      problems = {
        { id = 704, title = "Binary Search", slug = "binary-search", difficulty = "Easy" },
        { id = 74, title = "Search a 2D Matrix", slug = "search-a-2d-matrix", difficulty = "Medium" },
        { id = 875, title = "Koko Eating Bananas", slug = "koko-eating-bananas", difficulty = "Medium" },
        { id = 153, title = "Find Minimum in Rotated Sorted Array", slug = "find-minimum-in-rotated-sorted-array", difficulty = "Medium" },
        { id = 33, title = "Search in Rotated Sorted Array", slug = "search-in-rotated-sorted-array", difficulty = "Medium" },
        { id = 981, title = "Time Based Key-Value Store", slug = "time-based-key-value-store", difficulty = "Medium" },
        { id = 4, title = "Median of Two Sorted Arrays", slug = "median-of-two-sorted-arrays", difficulty = "Hard" },
      },
    },
    {
      name = "Linked List",
      problems = {
        { id = 206, title = "Reverse Linked List", slug = "reverse-linked-list", difficulty = "Easy" },
        { id = 21, title = "Merge Two Sorted Lists", slug = "merge-two-sorted-lists", difficulty = "Easy" },
        { id = 141, title = "Linked List Cycle", slug = "linked-list-cycle", difficulty = "Easy" },
        { id = 143, title = "Reorder List", slug = "reorder-list", difficulty = "Medium" },
        { id = 19, title = "Remove Nth Node From End of List", slug = "remove-nth-node-from-end-of-list", difficulty = "Medium" },
        { id = 138, title = "Copy List with Random Pointer", slug = "copy-list-with-random-pointer", difficulty = "Medium" },
        { id = 2, title = "Add Two Numbers", slug = "add-two-numbers", difficulty = "Medium" },
        { id = 287, title = "Find the Duplicate Number", slug = "find-the-duplicate-number", difficulty = "Medium" },
        { id = 146, title = "LRU Cache", slug = "lru-cache", difficulty = "Medium" },
        { id = 23, title = "Merge k Sorted Lists", slug = "merge-k-sorted-lists", difficulty = "Hard" },
        { id = 25, title = "Reverse Nodes in k-Group", slug = "reverse-nodes-in-k-group", difficulty = "Hard" },
      },
    },
    {
      name = "Trees",
      problems = {
        { id = 226, title = "Invert Binary Tree", slug = "invert-binary-tree", difficulty = "Easy" },
        { id = 104, title = "Maximum Depth of Binary Tree", slug = "maximum-depth-of-binary-tree", difficulty = "Easy" },
        { id = 543, title = "Diameter of Binary Tree", slug = "diameter-of-binary-tree", difficulty = "Easy" },
        { id = 110, title = "Balanced Binary Tree", slug = "balanced-binary-tree", difficulty = "Easy" },
        { id = 100, title = "Same Tree", slug = "same-tree", difficulty = "Easy" },
        { id = 572, title = "Subtree of Another Tree", slug = "subtree-of-another-tree", difficulty = "Easy" },
        { id = 235, title = "Lowest Common Ancestor of a BST", slug = "lowest-common-ancestor-of-a-binary-search-tree", difficulty = "Medium" },
        { id = 102, title = "Binary Tree Level Order Traversal", slug = "binary-tree-level-order-traversal", difficulty = "Medium" },
        { id = 199, title = "Binary Tree Right Side View", slug = "binary-tree-right-side-view", difficulty = "Medium" },
        { id = 1448, title = "Count Good Nodes in Binary Tree", slug = "count-good-nodes-in-binary-tree", difficulty = "Medium" },
        { id = 98, title = "Validate Binary Search Tree", slug = "validate-binary-search-tree", difficulty = "Medium" },
        { id = 230, title = "Kth Smallest Element in a BST", slug = "kth-smallest-element-in-a-bst", difficulty = "Medium" },
        { id = 105, title = "Construct Binary Tree from Preorder and Inorder", slug = "construct-binary-tree-from-preorder-and-inorder-traversal", difficulty = "Medium" },
        { id = 124, title = "Binary Tree Maximum Path Sum", slug = "binary-tree-maximum-path-sum", difficulty = "Hard" },
        { id = 297, title = "Serialize and Deserialize Binary Tree", slug = "serialize-and-deserialize-binary-tree", difficulty = "Hard" },
      },
    },
    {
      name = "Tries",
      problems = {
        { id = 208, title = "Implement Trie (Prefix Tree)", slug = "implement-trie-prefix-tree", difficulty = "Medium" },
        { id = 211, title = "Design Add and Search Words Data Structure", slug = "design-add-and-search-words-data-structure", difficulty = "Medium" },
        { id = 212, title = "Word Search II", slug = "word-search-ii", difficulty = "Hard" },
      },
    },
    {
      name = "Heap / Priority Queue",
      problems = {
        { id = 703, title = "Kth Largest Element in a Stream", slug = "kth-largest-element-in-a-stream", difficulty = "Easy" },
        { id = 1046, title = "Last Stone Weight", slug = "last-stone-weight", difficulty = "Easy" },
        { id = 973, title = "K Closest Points to Origin", slug = "k-closest-points-to-origin", difficulty = "Medium" },
        { id = 215, title = "Kth Largest Element in an Array", slug = "kth-largest-element-in-an-array", difficulty = "Medium" },
        { id = 621, title = "Task Scheduler", slug = "task-scheduler", difficulty = "Medium" },
        { id = 355, title = "Design Twitter", slug = "design-twitter", difficulty = "Medium" },
        { id = 295, title = "Find Median from Data Stream", slug = "find-median-from-data-stream", difficulty = "Hard" },
      },
    },
    {
      name = "Backtracking",
      problems = {
        { id = 78, title = "Subsets", slug = "subsets", difficulty = "Medium" },
        { id = 39, title = "Combination Sum", slug = "combination-sum", difficulty = "Medium" },
        { id = 46, title = "Permutations", slug = "permutations", difficulty = "Medium" },
        { id = 90, title = "Subsets II", slug = "subsets-ii", difficulty = "Medium" },
        { id = 40, title = "Combination Sum II", slug = "combination-sum-ii", difficulty = "Medium" },
        { id = 79, title = "Word Search", slug = "word-search", difficulty = "Medium" },
        { id = 131, title = "Palindrome Partitioning", slug = "palindrome-partitioning", difficulty = "Medium" },
        { id = 17, title = "Letter Combinations of a Phone Number", slug = "letter-combinations-of-a-phone-number", difficulty = "Medium" },
        { id = 51, title = "N-Queens", slug = "n-queens", difficulty = "Hard" },
      },
    },
    {
      name = "Graphs",
      problems = {
        { id = 200, title = "Number of Islands", slug = "number-of-islands", difficulty = "Medium" },
        { id = 133, title = "Clone Graph", slug = "clone-graph", difficulty = "Medium" },
        { id = 695, title = "Max Area of Island", slug = "max-area-of-island", difficulty = "Medium" },
        { id = 417, title = "Pacific Atlantic Water Flow", slug = "pacific-atlantic-water-flow", difficulty = "Medium" },
        { id = 130, title = "Surrounded Regions", slug = "surrounded-regions", difficulty = "Medium" },
        { id = 994, title = "Rotting Oranges", slug = "rotting-oranges", difficulty = "Medium" },
        { id = 207, title = "Course Schedule", slug = "course-schedule", difficulty = "Medium" },
        { id = 210, title = "Course Schedule II", slug = "course-schedule-ii", difficulty = "Medium" },
        { id = 684, title = "Redundant Connection", slug = "redundant-connection", difficulty = "Medium" },
        { id = 323, title = "Number of Connected Components", slug = "number-of-connected-components-in-an-undirected-graph", difficulty = "Medium" },
        { id = 127, title = "Word Ladder", slug = "word-ladder", difficulty = "Hard" },
      },
    },
    {
      name = "Advanced Graphs",
      problems = {
        { id = 332, title = "Reconstruct Itinerary", slug = "reconstruct-itinerary", difficulty = "Hard" },
        { id = 1584, title = "Min Cost to Connect All Points", slug = "min-cost-to-connect-all-points", difficulty = "Medium" },
        { id = 743, title = "Network Delay Time", slug = "network-delay-time", difficulty = "Medium" },
        { id = 787, title = "Cheapest Flights Within K Stops", slug = "cheapest-flights-within-k-stops", difficulty = "Medium" },
        { id = 269, title = "Alien Dictionary", slug = "alien-dictionary", difficulty = "Hard" },
      },
    },
    {
      name = "1-D Dynamic Programming",
      problems = {
        { id = 70, title = "Climbing Stairs", slug = "climbing-stairs", difficulty = "Easy" },
        { id = 746, title = "Min Cost Climbing Stairs", slug = "min-cost-climbing-stairs", difficulty = "Easy" },
        { id = 198, title = "House Robber", slug = "house-robber", difficulty = "Medium" },
        { id = 213, title = "House Robber II", slug = "house-robber-ii", difficulty = "Medium" },
        { id = 5, title = "Longest Palindromic Substring", slug = "longest-palindromic-substring", difficulty = "Medium" },
        { id = 647, title = "Palindromic Substrings", slug = "palindromic-substrings", difficulty = "Medium" },
        { id = 91, title = "Decode Ways", slug = "decode-ways", difficulty = "Medium" },
        { id = 322, title = "Coin Change", slug = "coin-change", difficulty = "Medium" },
        { id = 152, title = "Maximum Product Subarray", slug = "maximum-product-subarray", difficulty = "Medium" },
        { id = 139, title = "Word Break", slug = "word-break", difficulty = "Medium" },
        { id = 300, title = "Longest Increasing Subsequence", slug = "longest-increasing-subsequence", difficulty = "Medium" },
        { id = 416, title = "Partition Equal Subset Sum", slug = "partition-equal-subset-sum", difficulty = "Medium" },
      },
    },
    {
      name = "2-D Dynamic Programming",
      problems = {
        { id = 62, title = "Unique Paths", slug = "unique-paths", difficulty = "Medium" },
        { id = 1143, title = "Longest Common Subsequence", slug = "longest-common-subsequence", difficulty = "Medium" },
        { id = 309, title = "Best Time to Buy and Sell Stock with Cooldown", slug = "best-time-to-buy-and-sell-stock-with-cooldown", difficulty = "Medium" },
        { id = 518, title = "Coin Change II", slug = "coin-change-ii", difficulty = "Medium" },
        { id = 494, title = "Target Sum", slug = "target-sum", difficulty = "Medium" },
        { id = 97, title = "Interleaving String", slug = "interleaving-string", difficulty = "Medium" },
        { id = 329, title = "Longest Increasing Path in a Matrix", slug = "longest-increasing-path-in-a-matrix", difficulty = "Hard" },
        { id = 115, title = "Distinct Subsequences", slug = "distinct-subsequences", difficulty = "Hard" },
        { id = 72, title = "Edit Distance", slug = "edit-distance", difficulty = "Medium" },
        { id = 312, title = "Burst Balloons", slug = "burst-balloons", difficulty = "Hard" },
        { id = 10, title = "Regular Expression Matching", slug = "regular-expression-matching", difficulty = "Hard" },
      },
    },
    {
      name = "Greedy",
      problems = {
        { id = 53, title = "Maximum Subarray", slug = "maximum-subarray", difficulty = "Medium" },
        { id = 55, title = "Jump Game", slug = "jump-game", difficulty = "Medium" },
        { id = 45, title = "Jump Game II", slug = "jump-game-ii", difficulty = "Medium" },
        { id = 134, title = "Gas Station", slug = "gas-station", difficulty = "Medium" },
        { id = 846, title = "Hand of Straights", slug = "hand-of-straights", difficulty = "Medium" },
        { id = 1899, title = "Merge Triplets to Form Target Triplet", slug = "merge-triplets-to-form-target-triplet", difficulty = "Medium" },
        { id = 763, title = "Partition Labels", slug = "partition-labels", difficulty = "Medium" },
        { id = 678, title = "Valid Parenthesis String", slug = "valid-parenthesis-string", difficulty = "Medium" },
      },
    },
    {
      name = "Intervals",
      problems = {
        { id = 57, title = "Insert Interval", slug = "insert-interval", difficulty = "Medium" },
        { id = 56, title = "Merge Intervals", slug = "merge-intervals", difficulty = "Medium" },
        { id = 435, title = "Non-overlapping Intervals", slug = "non-overlapping-intervals", difficulty = "Medium" },
        { id = 252, title = "Meeting Rooms", slug = "meeting-rooms", difficulty = "Easy" },
        { id = 253, title = "Meeting Rooms II", slug = "meeting-rooms-ii", difficulty = "Medium" },
        { id = 1851, title = "Minimum Interval to Include Each Query", slug = "minimum-interval-to-include-each-query", difficulty = "Hard" },
      },
    },
    {
      name = "Math & Geometry",
      problems = {
        { id = 48, title = "Rotate Image", slug = "rotate-image", difficulty = "Medium" },
        { id = 54, title = "Spiral Matrix", slug = "spiral-matrix", difficulty = "Medium" },
        { id = 73, title = "Set Matrix Zeroes", slug = "set-matrix-zeroes", difficulty = "Medium" },
        { id = 202, title = "Happy Number", slug = "happy-number", difficulty = "Easy" },
        { id = 66, title = "Plus One", slug = "plus-one", difficulty = "Easy" },
        { id = 50, title = "Pow(x, n)", slug = "powx-n", difficulty = "Medium" },
        { id = 43, title = "Multiply Strings", slug = "multiply-strings", difficulty = "Medium" },
        { id = 2013, title = "Detect Squares", slug = "detect-squares", difficulty = "Medium" },
      },
    },
    {
      name = "Bit Manipulation",
      problems = {
        { id = 136, title = "Single Number", slug = "single-number", difficulty = "Easy" },
        { id = 191, title = "Number of 1 Bits", slug = "number-of-1-bits", difficulty = "Easy" },
        { id = 338, title = "Counting Bits", slug = "counting-bits", difficulty = "Easy" },
        { id = 190, title = "Reverse Bits", slug = "reverse-bits", difficulty = "Easy" },
        { id = 268, title = "Missing Number", slug = "missing-number", difficulty = "Easy" },
        { id = 371, title = "Sum of Two Integers", slug = "sum-of-two-integers", difficulty = "Medium" },
        { id = 7, title = "Reverse Integer", slug = "reverse-integer", difficulty = "Medium" },
      },
    },
  },
}
